#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

// dependency injection in case of this command. We are injecting the implementation
$builder = new \App\Application\Service\ClientBuilder();
$listBuilder = new \App\Application\Service\ClientListBuilder($builder);
$xmlClientListReader = new \App\Infrastructure\Service\XMLClientListReader($listBuilder);
$urlClientListReader =new \App\Infrastructure\Service\URLClientListReader($listBuilder);

$csvClientListWriter = new \App\Infrastructure\Service\CSVClientListWriter();
$application->add(new \App\Infrastructure\Command\ImportCommand(
        $xmlClientListReader, $urlClientListReader, $csvClientListWriter
));
$application->run();