<?php
namespace App\Tests\Infrastructure\Command;

use App\Application\Response\ClientListResponse;
use App\Infrastructure\Command\ImportCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ImportCommandStub extends ImportCommand
{
    public function getURL() : string
    {
        return self::URL;
    }
    public function readFiles( array $files) : ClientListResponse
    {
        return $this->readFiles($files);
    }

    public function execute(InputInterface $input, OutputInterface $output)
    {
        return parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}