<?php
namespace App\Tests\Infrastructure\Service;

use App\Application\Response\ClientListResponse;
use App\Application\Response\ClientResponse;
use App\Domain\Entity\Client;
use App\Domain\ValueObject\Company;
use App\Domain\ValueObject\Email;
use App\Domain\ValueObject\Name;
use App\Domain\ValueObject\Phone;
use App\Infrastructure\Service\CSVClientListWriter;
use PHPUnit\Framework\TestCase;

/**
 * @covers \App\Infrastructure\Service\CSVClientListWriter
 * @covers \App\Application\Service\ClientFormatter
 * @covers \App\Domain\Interface\ListWriter
 */
class CSVClientListWriterTest extends TestCase
{
    private CONST temp_file='/tmp/example.csv';

    /** @test */
    public function writer_must_create_file_in_tmp(): void
    {
        $response = $this->getClientListResponse();
        $writer = new CSVClientListWriter();

        $result = $writer->write($response, self::temp_file);
        self::assertEquals(true, $result);
        self::assertFileExists(self::temp_file);
    }

    private function getClientListResponse(): ClientListResponse
    {
        $response = new ClientListResponse();
        $client = new Client(
            new Name("test name"),
            new Email("test@email.com"),
            new Phone("999888777"),
            new Company("company test name")
        );
        $clientResponse = new ClientResponse($client);
        $response->addClientResponse($clientResponse);
        return $response;
    }

    public function tearDown(): void
    {
        //unlink(self::temp_file);
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
